# This is the docker compose config file
version: '3'

volumes:
  local_neo4j_data: {}

services:
  neo4j-db:
    image: neo4j:latest
    container_name: neo4j-db
    volumes:
      - local_neo4j_data:/data:Z
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]

